### ISSUE TITLE
Runtime error encountered: Cannot read property 'auditRefs' of undefined

### ISSUE THREAD

**Issue by keithbruss** [dvelasquez/lighthouse-plugin-crux#3]
When running a lighthouse test with lighthouse-plugin-crux enabled this error is thrown:

```
Runtime error encountered: Cannot read property 'auditRefs' of undefined
TypeError: Cannot read property 'auditRefs' of undefined
    at getMinScore (/usr/lib/node_modules/lighthouse-plugin-crux/lib/plugin.js:19:55)
    at Function.ReportScoring.scoreAllCategories (/usr/lib/node_modules/lighthouse-plugin-crux/lib/plugin.js:15:33)
    at Function.run (/usr/lib/node_modules/lighthouse/lighthouse-core/runner.js:127:36)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async runLighthouse (/usr/lib/node_modules/lighthouse/lighthouse-cli/run.js:245:8)
```

Here is the cmd:

`lighthouse "https://site.com" --channel wpt --only-categories performance,seo,accessibility,best-practices --enable-error-reporting --max-wait-for-load 80000 --port 9223 --plugins lighthouse-plugin-crux --output html --output json --output-path "/tmp/" --throttling-method simulate --throttling.requestLatencyMs 0 --throttling.downloadThroughputKbps 0 --throttling.uploadThroughputKbps 0 --throttling.cpuSlowdownMultiplier 4.300 --skip-audits screenshot-thumbnails,final-screenshot --form-factor mobile --chrome-flags="--disable-dev-shm-usage --user-agent='Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4) Build/MPJ24.139-64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/65.0.3325.146 Mobile Safari/537.36 speed2/210721.145320'"`

**Comment by dvelasquez** [comment]
Hey @keithbruss , which version of lighthouse are you using?

**Comment by keithbruss** [comment]
@dvelasquez 
$ lighthouse --version
8.3.0

**Comment by dvelasquez** [comment]
Thanks for the info @keithbruss 

In Lighthouse, each category it's a plugin by itself. So the problem with your cli command is that you are not adding `lighthouse-plugin-crux` to the lists of categories.

So now your command looks like this: `--only-categories performance,seo,accessibility,best-practices`

And it should be: `--only-categories performance,seo,accessibility,best-practices,lighthouse-plugin-crux`

This is true for any plugin you use in lighthouse. Please try this commmand and let me know if it works:
`lighthouse "https://site.com" --channel wpt --only-categories performance,seo,accessibility,best-practices,lighthouse-plugin-crux --enable-error-reporting --max-wait-for-load 80000 --port 9223 --plugins lighthouse-plugin-crux --output html --output json --output-path "/tmp/" --throttling-method simulate --throttling.requestLatencyMs 0 --throttling.downloadThroughputKbps 0 --throttling.uploadThroughputKbps 0 --throttling.cpuSlowdownMultiplier 4.300 --skip-audits screenshot-thumbnails,final-screenshot --form-factor mobile --chrome-flags="--disable-dev-shm-usage --user-agent='Mozilla/5.0 (Linux; Android 6.0.1; Moto G (4) Build/MPJ24.139-64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/65.0.3325.146 Mobile Safari/537.36 speed2/210721.145320'"`

Thanks again for opening the issue, I will update the documentation with this information too 👍
