### ISSUE TITLE
Update CrUX FID field to CrUX INP

### ISSUE THREAD

**Issue by r3fresh** [dvelasquez/lighthouse-plugin-crux#727]
Hello !

Since lighthouse replaced CrUX FID metric by CrUX INP (Interactive to Next Paint) can you update this metric in this repo as well ?
Support will end on September as mentionned there : https://developer.chrome.com/docs/crux/methodology/metrics#fid-metric

Cheers !

**Comment by dvelasquez** [comment]
Thanks @r3fresh for opening an issue.

I'll take a look. I have pending do a general update to make it full compatible with lighthouse v12 which changed everything from cjs to esm.

I'll link this issue to the PR solving both cases.

**Comment by dvelasquez** [comment]
The changes are available in the new version `0.1.0`

Let me know how it goes.

**Comment by r3fresh** [comment]
I will try ASAP, thanks !

**Comment by r3fresh** [comment]
@dvelasquez Works like a charm  for me. Thanks for the update ! This issue can be closed.
